### PR TITLE
chore: add @ui-kitten/metro-config package

### LINKED ISSUE #613: ApplicationProvider shouldn't process mappings everytime it's mounted
**I'm submitting a ...** 

* [ ] bug report
* [ x] feature request

### Issue description
This is not an issue with UI Kitten itself, but rather a request to make play well with a very popular library (react-native-navigation by Wix) and maybe others.

**Current behavior:**
In order to use the framework with its theming capabilities we should wrap our app with UI Kitten ApplicationProvider.
ApplicationProvider uses Eva System to process mapping schemas upon its construction, which takes a couple of seconds on an average Android phone (Which is fine).

Now, In case we're using react-navigation as a navigation solution, ApplicationProvider will be mounted only once at startup (process mapping once), and then all the navigation will take place inside that provider node, and there are no issues in this case.

however, if react-native-navigation is being used, and as you may know, it works by registering each screen component individually and in isolation of others after the app is launched, we have to wrap each screen component with whatever providers being used, including redux, and in this case, UI Kitten ApplicationProvider, thus, whenever a page is being pushed or a modal being shown, the Application provider will process the mapping again which is causing a few seconds delay before the screen component being mounted.

**Expected behavior:**
Unless mapping prop has changed, Application provider should use a pre-processed data from previous component construction.

**Steps to reproduce:**
It can be simply reproduced by using react-native-navigation with UI Kitten.

### Other information:

**OS, device, package version**
```
React-native 0.60
Platforms: Android, iOS
UI Kitten Version: 4.1.0
react-native-navigation: 3.0.0
```

### LINKED ISSUE #855: Updating custom-mapping.json make the application very slow to load
## 🐛 Bug Report

After having updated the `custom-mapping.json` file, our loading time jumped from few seconds to approximatively 15 ! In our modifications possibly involved, we pointed :
- Passing json file to multiples js files
- Adding `states` variants into `Button` component mapping (verified)

## To Reproduce

- Install and configure project with UI Kitten
- Add new `states` on Buttons component mapping in `custom-mapping.json` for example 
- Get your timer and compile then launch

## Expected behavior

The application compile and load with no more significant delay

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   1.3.0    |
| react-native-ui-kitten   |  4.3.1  |

## Environment information

```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
```

### PR DESCRIPTION
**Pull request by artyorsh**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

Computes Eva styles during the build time allowing the application load much faster.

- Closes #613
- Closes #855 

<hr>

#### Integration ([Guide](https://github.com/akveo/react-native-ui-kitten/blob/a7410e32a69e0f135b1048c02492f172188c2421/docs/src/articles/guides/improving-performance.md#improving-performance))

1. `yarn add -D @ui-kitten/metro-config`
2. Add or modify **metro.config.js** with following configuration
```diff
+ const MetroConfig = require('@ui-kitten/metro-config');

+ const evaConfig = { 
+   evaPackage: '@eva-design/eva', // Required (Can be `@eva-design/material`)
+   customMappingPath: './custom-mapping.json', // Optional
+ };

+ module.exports = MetroConfig.create(evaConfig, {
+   // Whatever was in previous metro.config.js 
+ });
```
3. Modify props of ApplicationProvider
```diff
- import { mapping, light } from '@eva-design/eva';
+ import * as eva from '@eva-design/eva'; 
- import { customMapping } from './custom-mapping.js'

export default = () => (
- <ApplicationProvider mapping={mapping} theme={light} />
+ <ApplicationProvider {...eva} theme={eva.light} />
);
```

#### Limitations

Not compatible with Fast Refresh - will reload app completely whenever custom mapping is changed if it is used.

#### [How it works](https://github.com/akveo/react-native-ui-kitten/blob/e5a94a67afd9f1e28cc256df1065f1001060fa3f/src/metro-config/services/bootstrap.service.ts#L41)

### CODE REVIEW

**Comment by TranDinhKhang** [comment]
please merge this, my app have issues with the boot time. approx 6 - 7 secs for fully loaded :(

**Comment by artyorsh** [comment]
@TranDinhKhang do you use custom mapping or React Native Navigation by Wix?

**Comment by YIZHUANG** [comment]
@artyorsh have you tested this change reduce the load time to almost 0?

**Comment by artyorsh** [comment]
@YIZHUANG yes, I already run it locally in [Kitten Tricks](https://github.com/akveo/kittentricks)

**Comment by YIZHUANG** [comment]
How can i use this already before its merge besides making my own fork?

**Comment by YIZHUANG** [comment]
@artyorsh nice, good job!

**Comment by YIZHUANG** [comment]
Any guides on how i can test this in my app already before it's merged?

**Comment by YIZHUANG** [comment]
I ended up just copying the end output (2.6mb) json, and remove the "process" function

**Pull request merged**
