### PR TITLE
fix(select): height for android to match ios

### PR DESCRIPTION
**Pull request by jorgnyg**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves: fixing the height gap for select component on android vs. ios. Was not able to find the root cause, so would appreciate suggestions

### CODE REVIEW

**Comment by artyorsh** [comment]
@jorgnyg Thanks for opening a PR!
This will break the `size` property, I think :) Have you checked that?
The correct way to fix it is inspecting eva mappings and synchronize it with Input, I suppose.

**Comment by jorgnyg** [comment]
> @jorgnyg Thanks for opening a PR!
> This will break the `size` property, I think :) Have you checked that?
> The correct way to fix it is inspecting eva mappings and synchronize it with Input, I suppose.

Yep this breaks the "size" prop.. But thanks for pointing me in the right direction!
I'm taking a look at the mappings from eva design, but how do I check for platform specific code? Weird thing here is that the input and select size is correct for iOS, but not on android 🤔

**Comment by artyorsh** [comment]
@jorgnyg I'm not sure, but it can be a platform-specific implementation on the react-native level. Needs investigation. The other notice: we removed `lineHeight` properties for each component in v5, which also probably could affect.

**Comment by jorgnyg** [comment]
@artyorsh I understand. In the meantime, how can I use my not-so-ideal hotfix fork as a dependency for my project? Want to keep all of your code in addition to the one line I added to temporary "unblock" my project.

**Comment by artyorsh** [comment]
@johanquiroga you may clone the repo and configure babel and metro to use the library locally. For the reference, you may see how it's done in [Kitten Tricks](https://github.com/akveo/kittenTricks). We use it for debugging the library.

**Comment by artyorsh** [comment]
@jorgnyg here's the [working fix](https://github.com/akveo/react-native-ui-kitten/pull/1055/commits/70e1b52efe495aa063aaab90ecd71a119913acab), you may track it [here](https://github.com/akveo/react-native-ui-kitten/pull/1055)

**Pull request closed without merging**
