### PR TITLE
fix(components): select - pass testID to TouchableWeb

### PR DESCRIPTION
**Pull request by crkshnks**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Currently, the Select component does not pass the testID prop to the TouchableWeb component. This pull request fixes that.

### CODE REVIEW

**Comment by artyorsh** [comment]
👋 
Thanks for opening a PR.
IMO, if it is done for a single component, it should be done for the rest. Could you explain the purpose of adding this? I know for tests, but please describe your use case.
Internally, we use [react-native-testing-library](https://github.com/callstack/react-native-testing-library), and [it's not an issue not having `testID`s for us to test](https://github.com/akveo/react-native-ui-kitten/blob/next/src/components/ui/select/select.spec.tsx#L150).

**Comment by samufort** [comment]
@artyorsh 

We need this PR to easily control our tests such as opening the select, checking / unchecking checkboxes, etc. We also use `react-native-testing-library`. Not passing testID will in a near future be an issue if you want to update your testing library since as of versions 2.0, you need to prefix the `byType` query with `UNSAFE_`. This query will eventually be removed from the library. 

For our end-to-end test suite (`Detox`), this is also annoying since our tests are weakened due to the need to query by text.

We encountered this with the CheckBox, Select and SelectItem components

**Comment by malashkevich** [comment]
I agree it would be nice to have testID's on all components, not just select.

**Comment by malashkevich** [comment]
Closing in favor of #1352

**Pull request closed without merging**
