### PR TITLE
fix(components): FalsyFC should be able to render components with hooks

### LINKED ISSUE #1015: v5 breaks support for functional components with hooks in accessories
## 🐛 Bug Report
v5 breaks support for rendering components with hooks in props such as `accessoryLeft` due to the implementation of: https://github.com/akveo/react-native-ui-kitten/blob/next/src/components/devsupport/components/falsyFC/falsyFC.component.tsx

`FalsyFC` should not make the assumption that components are plain functions. It should properly use `React.createElement` so hooks continue working.

## To Reproduce
```
const MyHookComponent = () => {
        const [name, setName] = React.useState('');
        React.useEffect(() => {
              setName('test');
        });

        return <Text>{name}</Text>;
};

const MyApp = () => (
        <TopNavigation
                accessoryLeft={MyHookComponent}
                title={"test"}
          />
);
```

## Expected behavior

For `FalsyFC` to render components with hooks by properly using `React.createElement`.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  2.0.0-alpha.1      |
| @ui-kitten/components   | 5.0.0-alpha.1        |

### PR DESCRIPTION
**Pull request by Photonios**
Closes #1015

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

### CODE REVIEW

**Comment by artyorsh** [comment]
@Photonios thanks for working on this! I've some changes locally already, it also includes changes for `falsyText`, which is used for text properties. I plan to open PR with a list of bug fixes for other teammates review and hopefully we'll have `stable` soon 👍

**Comment by Photonios** [comment]
@artyorsh Thanks for the quick response.

Since you've already made the changes in your local branch, does that mean I should close the PR and patiently wait for your fixes to be released?

**Comment by artyorsh** [comment]
@Photonios I would be glad to cherry-pick your job into the PR I plan to open soon. But I would suggest fixing this for `falsyText` as well :)

**Comment by Photonios** [comment]
@artyorsh Sure! I'll do that in like an hour. I'lll have to finish my dinner first. I'll also address the typing error.

**Comment by Photonios** [comment]
@artyorsh Done! Updated `FalsyText` as well and updated the typings.

**Comment by artyorsh** [comment]
Thanks @Photonios! 👍

**Pull request merged**
