### PR TITLE
update: add new condition for tabIndicator render

### LINKED ISSUE #1237: TabIndicator style is not updated
## 🐛 Bug Report

The style of `TabBar`s `indicatorStyle` is not updated after a change because `shouldComponentUpdate` only checks if the index was changed. Other props are ignored. 

I attached a snack illustrating the issue.

I tried creating a PR fixing the issue but unfortunately adding another check for style in `shouldComponentUpdate` in `tabIndicator.component.tsx` causes the app to crash with "Attempted to remove more RCTNativeAnimatedModule listeners than added". 
Setting `useNativeDriver` to false in  `createOffsetAnimation` (same file) fixes the issue entirely but since it might impact other things I'd like to consult the change in this issue first. 

`shouldComponentUpdate`:
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/shared/tabIndicator.component.tsx#L39

`createOffsetAnimation`:
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/shared/tabIndicator.component.tsx#L95

## To Reproduce

1. Create TabBar
2. Try to change `indicatorStyle` to a different value without changing the tab index. 

## Expected behavior

Update indicatorStyle when it changes.

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/@andrzjugsziejestes/tabbarissueplayground

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0   |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.5 - ~/repos/tab_bar_test_repo/node_modules/.bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.13.1 
    react-native: ^0.61.5 => 0.61.5 
```

### PR DESCRIPTION
**Pull request by whitestranger7**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Closes #1237

### CODE REVIEW

**Comment by whitestranger7** [comment]
Btw, regarding all `TabIndicator` states, I don't think we need shouldComponentUpdate condition at all

**Comment by artyorsh** [comment]
> Btw, regarding all `TabIndicator` states, I don't think we need `shouldComponentUpdate` condition at all

Yep, it worth testing it without any condition then. And probably we're fine with removing `shouldComponentUpdate` then. Could you check that?

**Comment by whitestranger7** [comment]
the problem with `nativeDriver` is that for some reason it calls an error with animation when `shouldComponentUpdate` removed. Im still figuring out what's the problem with it, but are we really need this `nativeDriver` right there?

**Comment by artyorsh** [comment]
> the problem with `nativeDriver` is that for some reason it calls an error with animation when `shouldComponentUpdate` removed. Im still figuring out what's the problem with it, but are we really need this `nativeDriver` right there?

It worth using it when possible for having better performance. With this flag enabled, you will have animations running [on the UI thread and not through the bridge](https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated#what-is-this).

**Comment by whitestranger7** [comment]
Still not sure why it's crushes when ```nativedriver: true ``` applied =(

**Comment by AntonBorovoi** [comment]
@whitestranger7 It works fine for me with the removed `shouldComponentUpdate` on clean project.
However I am getting crashes on kitten-tricks project too.

During investigation I found that the app crash because of `NaN` value which was set on animation definition
```
return Animated.timing(this.contentOffset, {
      toValue: RTLService.select(params.offset, -params.offset),
      duration: 200,
      easing: Easing.linear,
      useNativeDriver: Platform.OS !== 'web',
    });
```
after calculations goes into
```
return Animated.timing(this.contentOffset, {
      toValue: NaN,
      duration: 200,
      easing: Easing.linear,
      useNativeDriver: true,
    });
```

The reason why `params.offset` is NaN is on this line `const offset: number = this.indicatorWidth * index;(undefined*0=NaN)`
`indicatorWidth` doesn't have any initial value(`private indicatorWidth: number;`) and it is setting only after `onLayout` call 

The reason why it is not working on kitten-tricks: top components re-render for some reasons and it leads to tabBar re-render and as result 
```
public componentDidUpdate(prevProps) {
    const { selectedPosition: index } = this.props;

    this.scrollToIndex({
      index,
      animated: true,
    });
  }
```
called before `onLayout`.



In order to fix the initial issue I guess we have to remove `shouldComponentUpdate` and set a default value for `indicatorWidth` by `private indicatorWidth: number = 0`

**Pull request closed without merging**
