### PR TITLE
Added dateFormat customization to datepicker

### LINKED ISSUE #815: Enable string localization on DatePicker
## 🚀 Feature Proposal

Currently only DD/MM/YYYY format is supported to be displayed on the datepicker component with no way to over-ride this or set a custom localization string. 

## Motivation

This is just super inconvenient for anyone living in America. Please add support for specifying any datestring 
image

## Example

Add a property to the datePicker components of localizationString

### PR DESCRIPTION
**Pull request by nutritiousreject**
Added support for manually specifying the date format on thhe 
### Please read and mark the following check list before creating a pull request:

 - [X] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [X] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Previously date formats were hard-coded into the DD-MM-YYYY format, which is a huge PITA if you're an american who uses backwards ass date formats.

You can now specify what format you would like your date to display in by passing the dateFormat property into the component as follows

`        <Datepicker
          date={this.state.date}
          onSelect={(date) => {this.selectDate(date)}}
          dateFormat='MM-DD-YYYY'
        />
`

I've built the project and ran it myself to confirm it works.

Closes #815

### CODE REVIEW

**Comment by artyorsh** [comment]
Thanks for opening a PR! I like the idea, but I guess it's better to do this with [fecha](https://github.com/taylorhakes/fecha), which is included as a dependency to perform date operations in this library. I will investigate this feature and use your PR for this. Contributions are welcome 👐

**Comment by nutritiousreject** [comment]
I'll see if I can integrate fetcha into the string localization when i'm at work today and push another commit to the PR. Usually its slow as heck

**Comment by nutritiousreject** [comment]
Just want to make sure i'm not missing anything. 

`this.props.dateService.format(date, date)`

Which gets defined in
```
 static defaultProps: Partial<BaseDatepickerProps> = {
    dateService: new NativeDateService(),
```
And the date service gets imported from 
`import { NativeDateService } from '../calendar/service/nativeDate.service';`

And the format function being called in nativeDate.service.ts in my change is 

```

  public format(date: Date, format: string): string {
    return fecha.format(date, format);
  }

```

So no changes should be necessary?  The only difference is allowing users to specify the string instead of hardcoding it as a const. Fecha was already doing the string localization to begin with, just with a hardcoded date format

**Comment by artyorsh** [comment]
@nutritiousreject yes. You may need to call `format` [here](https://github.com/akveo/react-native-ui-kitten/blob/709dbe92795233359626ef94121270b33b41ee00/src/components/ui/datepicker/datepicker.component.tsx#L117). Same for [Range Datepicker](https://github.com/akveo/react-native-ui-kitten/blob/709dbe9279/src/components/ui/datepicker/rangeDatepicker.component.tsx#L103)

**Pull request merged**
