### PR TITLE
fix: TabView and shouldLoadComponent bounces between tabs #1234

### PR DESCRIPTION
**Pull request by bataevvlad**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

### CODE REVIEW

**Review by greenfrvr — APPROVED** [review]

**Comment by KieQuang** [comment]
still not working. 
IP 12 simulator (iOS 16.2)

**Comment by greenfrvr** [comment]
@KieQuang  Could you please tell, how did you check it?

**Comment by KieQuang** [comment]
I have an issue. I have 3 tabs and it have same height, to solve it i used shouldLoadComponent but it jumb between 2 tabs. Give me a sec I send clip.

**Comment by KieQuang** [comment]
https://github.com/akveo/react-native-ui-kitten/assets/87011701/f2b0da13-e299-4239-ad56-0bb3914b3840

**Comment by KieQuang** [comment]
Screen Shot 2023-06-20 at 18 18 34

**Pull request merged**
