### PR TITLE
Fix testID on Input component

### LINKED ISSUE #1490: testID is assigned to both TouchableWithoutFeedback component and TextInput component for the Input component
## 🐛 Bug Report

Commit #1435  adds a regression, and in my case broke a lot of tests.

`await element(by.id('email')).replaceText('EMAIL');`
This no longer works since testID is now assigned to parent TouchableWithoutFeedback component, this results in replaceText failing.

In the case of the Input component the testID is assigned to both TouchableWithoutFeedback component and TextInput component which makes it extra confusing.

At the moment using Detox I could not find a cross platform way to populate the Input component.

Downgrading to 5.1.0 fixed the issue.

### PR DESCRIPTION
**Pull request by codebutler**
### Please read and mark the following check list before creating a pull request:

 - [X] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [X] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

Fixes #1490

### CODE REVIEW

**Comment by manuelmhtr** [comment]
Please merge this 🙏

**Review by flexbox — APPROVED** [review]
Sounds Good To Me :)

**Comment by effektsvk** [comment]
Hi, is there a chance this is getting merged and released? Thanks 😊

**Comment by greenfrvr** [comment]
@codebutler hey, I'm not sure if anyone is relying on current `testID` prop, which is used by `TouchableWithoutFeedback`. What do you think about adding some prefix to passed value of `testID` and use it for `TouchableWithoutFeedback` wrapper? This way we'll have both components having test ids which I believe should allow to cover all test cases

**Comment by greenfrvr** [comment]
@codebutler I've create PR #1685 for the issue. the difference with this one is that I'm using parameterized testIDs so that touchable container and text input both would be accessible for different test cases. closing this PR

**Pull request closed without merging**
