### PR TITLE
fix(autocomplete): fixed the double-click required to select an item …

### PR DESCRIPTION
**Pull request by AlexBatorykLeliw**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

There is a bug in the auto-suggest which requires the user to click out of the keyboard before selecting an item on the list. This line solves this issue by utilising the **keyboardShouldPersistTaps** prop from ScrollView (and by extension FlatList, which is what in under the hood of autocomplete). I leave this hardcoded as I don't suggest you would want the current behaviour in any scenario.

Please see below, current behaviour vs fix:

https://user-images.githubusercontent.com/10847190/117220214-b1219a80-adfe-11eb-8fd1-eab7f011d8ff.mov

https://user-images.githubusercontent.com/10847190/117220221-b252c780-adfe-11eb-803f-137bd2b2c4da.mov

### CODE REVIEW

**Review by whitestranger7 — APPROVED** [review]

**Review by malashkevich — APPROVED** [review]

**Comment by Gondolav** [comment]
Hello, when will this fix be available?

**Comment by BenMillsPerkins** [comment]
Hi, when will this be tagged and released please?

**Comment by Gondolav** [comment]
Hi, it doesn't seem to work with autocomplete components inside scrollviews, any ideas why?

**Comment by AntonBorovoi** [comment]
Hi @Gondolav 
Do you mean that here might be a need to add a new prop to control `keyboardShouldPersistTaps` on component itself?

**Comment by Gondolav** [comment]
Hi, while testing it would work only by setting manually to `handled`, but cleaning and re-installing made it work as it is now with `always`, so I guess for now there is no such need.

**Pull request merged**
