### PR TITLE
fix(ui): view-pager in RTL mode

### PR DESCRIPTION
**Pull request by sijav**
#### Short description of what this resolves:
This will fix view pager on RTL:
  - This will fix view pager animations on RTL
  - This will fix view pager index on RTL
  - This will fix the user interaction with view pager on RTL
  - This will fix tab view on RTL

Note: this PR works best with #558

### CODE REVIEW

**Comment by artyorsh** [comment]
Thanks a lot! We're currently working on this. Do you have any other patches?

**Comment by sijav** [comment]
@artyorsh Yes I actually have everything covered I will make PR request per every items

**Comment by artyorsh** [comment]
@sijav Let's close this one and #558 so you can create a single PR. Actually, I started working on RTL support yesterday, an I did it in a bit another and efficient way. Let's create a single PR so we can merge our changes, and you could see the idea

**Comment by sijav** [comment]
@artyorsh oh ok I created another PR please close the other one too

**Pull request closed without merging**
