### PR TITLE
refactor(components): update useStyleSheet hook

### LINKED ISSUE #831: useStyleSheet hook doesn't follow Hook rules
## 🐛 Bug Report

Using the hook `useStyleSheet` with ESlint Hook rules doesn't work. The code works when disabling the rule with `// eslint-disable-next-line react-hooks/rules-of-hooks`.
https://reactjs.org/docs/hooks-rules.html#eslint-plugin

## To Reproduce

1. Follow instructions in https://akveo.github.io/react-native-ui-kitten/docs/components/themed-component/overview#usestylesheet.

```typescript
import React from 'react';
import {
  Layout,
  Text,
  useStyleSheet,
} from '@ui-kitten/components';

export const UseStyleSheetSimpleUsageShowcase = () => {
  const styles = StyleSheet.create();

  return (
    <Layout style={styles.container}>
      <Text category='h4' status='control'>
        I use success color as background!
      </Text>
    </Layout>
  );
};

const StyleSheet = useStyleSheet({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'color-success-default',
  },
});
```

## Expected behavior

No warnings/errors should show up.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    4.4.0-beta.2    |
| @ui-kitten/components   |      4.4.0-beta.2   |

## Environment information

```bash

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

### PR DESCRIPTION
**Pull request by artyorsh**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

Creates a new service for creating themed styles and updates `useStyleSheet` hook due to [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html)

Discussed by users in #782 
Closes #831 

**New syntax:**

```diff
import React from 'react';
- import { Layout, useStyleSheet } from '@ui-kitten/components';
+ import { Layout, StyleService, useStyleSheet } from '@ui-kitten/components';

export const UseStyleSheetSimpleUsageShowcase = () => {
-  const styles = StyleSheet.create();
+ const styles = useStyleSheet(themedStyles);

  return (
    <Layout style={styles.container} />
  );
};

- const StyleSheet = useStyleSheet({
+ const themedStyles = StyleService.create({
  container: {
    flex: 1,
    backgroundColor: 'color-success-default',
  },
});
```

### CODE REVIEW

**Comment by fvieira** [comment]
Thanks for hearing our feedback, @artyorsh.
This is much better, definitely. 

I still have a small gripe that we're using `StyleSheet.create` to return not an actual stylesheet (the `styles` variable) as the name implies, but a hook.
I understand that we're trying to keep the `StyleSheet.create` that RN users are used to, but users are also used to it returning a `styles` variable, so this might actually work against us, they might just change the `StyleSheet` import from `react-native` to `@ui-kitten/components` and then wonder why the code is not working.

My recommendation would be to rename it to `StyleSheet.createHook`. This way, if they just change the import, the code breaks as it should (or Typescript complains the `create` method does not exist), they can use autocomplete to find out the name of the new method (`createHook`), which in turn acts as a reminder that a hook is returned, not the styles themselves.

**Comment by artyorsh** [comment]
@fvieira Well, after small brainstorming we decided to rename a service, not a function. In general, this `create` method does absolutely nothing, unlike RN StyleSheet which does validation and styles registering. We just can't use it because [it does not support style preprocessing currently](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js#L325). But I think it is useful to have it in order to support the syntax we used to. [See more details](https://github.com/akveo/react-native-ui-kitten/pull/833/files#diff-1ba13e452fa599615f964152ac9a0a38R56)

The main functionality is back again in `useStyleSheet` which does all processing stuff.

**Comment by fvieira** [comment]
@artyorsh I think this new nomenclature fixes all problems with the previous ones, I see nothing misleading about it now!

**Comment by vomchik** [comment]
@artyorsh Nice! I really like a new approach. Thanks.

I see only one flaw,  it is a typing for theme variables. `color-primary-default` looks like a magic string.  But I guess we can improve it in the future :)

**Pull request merged**
